version: 1
last_updated: 2026-02-12T04:45:50.641Z
fingerprint: 3da3d665
scope: src/providers
summary: >
  The `src/providers` directory contains multiple implementations of a language model provider interface, allowing
  interaction with different AI models from various vendors through a unified API.
files:
  - name: anthropic.ts
    purpose: Implementation of the Anthropic language model provider.
  - name: google.ts
    purpose: Implementation of the Google language model provider.
  - name: index.ts
    purpose: Defines the LLMProvider interface and a factory function to create provider instances.
  - name: ollama.ts
    purpose: Implementation of the Ollama language model provider.
  - name: openai.ts
    purpose: Implementation of the OpenAI language model provider.
maintenance: |-
  If you modify files in this directory, update this .context.yaml to reflect
  your changes. Update the files list, interfaces, and current_state sections.
  Do NOT update the fingerprint manually — run `context rehash` or it will be
  updated automatically on the next `context status` check.
  If you only read files in this directory, do not modify this file.
  Do not include secrets, API keys, passwords, or PII in this file.
interfaces:
  - name: LLMProvider
    description: Abstract interface for language model providers with a method to generate responses.
  - name: createProvider
    description: Factory function that creates an instance of a specified language model provider.
decisions:
  - what: Providers are implemented as separate classes.
    why: To isolate the logic and dependencies of each language model, allowing for modularity and easier maintenance.
    tradeoff: Increased complexity due to handling multiple classes instead of a single implementation.
dependencies:
  internal:
    - ./index.js
derived_fields:
  - version
  - last_updated
  - fingerprint
  - scope
  - dependencies.internal
