version: 1
last_updated: 2026-02-12T04:45:47.378Z
fingerprint: 919ad02b
scope: src/core
summary: >
  The src/core directory contains utilities for managing project fingerprints, markdown generation for agents, and
  scanning directory structures for context data. It provides functions for calculating file fingerprints, reading and
  writing markdown files, and scanning project directories for relevant files.
files:
  - name: fingerprint.ts
    purpose: Computes and checks the fingerprint of a directory based on its files.
  - name: markdown-writer.ts
    purpose: Reads and writes AGENTS.md files, and manages updates to the content.
  - name: scanner.ts
    purpose: Scans a directory tree to find directories that should have .context.yaml files.
  - name: schema.ts
    purpose: Defines the schemas for context and config files using Zod.
  - name: writer.ts
    purpose: Handles reading and writing of .context.yaml and .context.config.yaml files.
maintenance: |-
  If you modify files in this directory, update this .context.yaml to reflect
  your changes. Update the files list, interfaces, and current_state sections.
  Do NOT update the fingerprint manually — run `context rehash` or it will be
  updated automatically on the next `context status` check.
  If you only read files in this directory, do not modify this file.
  Do not include secrets, API keys, passwords, or PII in this file.
interfaces:
  - name: computeFingerprint
    description: Calculates a fingerprint based on file metadata in a specified directory.
  - name: checkFreshness
    description: Compares the computed fingerprint of a directory with a stored fingerprint.
  - name: readAgentsMd
    description: Reads the AGENTS.md file from the project root, returning null if not found.
  - name: writeAgentsMd
    description: Writes the AGENTS.md file to the project root.
  - name: updateAgentsMd
    description: Orchestrates the update process for AGENTS.md, determining whether to create, append, or replace content.
  - name: scanProject
    description: Initiates a scan of the project directory for .context.yaml candidates.
  - name: readContext
    description: Reads and parses the .context.yaml file.
  - name: writeContext
    description: Writes a ContextFile to disk as .context.yaml.
  - name: readConfig
    description: Reads the configuration file from disk.
  - name: writeConfig
    description: Writes the configuration file to disk.
decisions:
  - what: Use of Zod for schema validation.
    why: Ensures the data integrity of context and config files by enforcing predefined structures.
    tradeoff: Increased complexity in managing validations.
dependencies:
  internal:
    - ../generator/markdown.js
    - ./schema.js
current_state:
  working:
    - Functions to compute fingerprints, read/write markdown, and scan directories are functional.
  broken:
    - No known broken functionalities at present.
  in_progress:
    - Refining the scanning algorithm for better performance.
derived_fields:
  - version
  - last_updated
  - fingerprint
  - scope
  - dependencies.internal
