version: 1
last_updated: 2026-02-12T01:27:56.117Z
fingerprint: 46b2bea9
scope: docs
summary: >
  This directory provides documentation and guidance for integrating dotcontext in CI/CD pipelines, detailing command
  usage, integration with various tools, limitations, and troubleshooting steps.
files:
  - name: ci.md
    purpose: Documentation for CI/CD pipeline integration and usage with dotcontext.
  - name: integrations.md
    purpose: Guidance on integrating dotcontext with external tools and environments.
  - name: limitations.md
    purpose: Documentation of known limitations related to dotcontext functionality.
  - name: quickstart.md
    purpose: A rapid guide to getting started with dotcontext.
  - name: schema.md
    purpose: Reference for the schema structure of .context.yaml files.
  - name: troubleshooting.md
    purpose: Help with common issues and their solutions.
  - name: trust-model.md
    purpose: Explains the trust model of field provenance in .context.yaml files.
  - name: validation.md
    purpose: Details on how to validate .context.yaml files for correctness.
maintenance: |-
  If you modify files in this directory, update this .context.yaml to reflect
  your changes. Update the files list, interfaces, and current_state sections.
  Do NOT update the fingerprint manually — run `context rehash` or it will be
  updated automatically on the next `context status` check.
  If you only read files in this directory, do not modify this file.
  Do not include secrets, API keys, passwords, or PII in this file.
derived_fields:
  - version
  - last_updated
  - fingerprint
  - scope
